package com.datamation.hmdsfa.model;

public class PaymentAllocate {

    private String FPAYMENT_ALLOCATE_ID;
    private String FPAYMENT_ALLOCATE_REFNO;
    private String FPAYMENT_ALLOCATE_FDD_REFNO;
    private String FPAYMENT_ALLOCATE_FDD_TXN_DATE;
    private String FPAYMENT_ALLOCATE_FDD_PAID_AMT;
    private String FPAYMENT_ALLOCATE_FDD_TOTAL_BAL;
    private String FPAYMENT_ALLOCATE_PAY_REF_NO;
    private String FPAYMENT_ALLOCATE_PAY_MODE;
    private String FPAYMENT_ALLOCATE_PAY_DATE;
    private String FPAYMENT_ALLOCATE_PAY_AMT;
    private String FPAYMENT_ALLOCATE_PAY_REM_AMT;
    private String FPAYMENT_ALLOCATE_PAY_ALLO_AMT;
    private String FPAYMENT_ALLOCATE_PAY_BANK;
    private String FPAYMENT_ALLOCATE_PAY_CHEQUE_NO;
    private String FPAYMENT_ALLOCATE_PAY_CREDIT_CARD_NO;
    private String FPAYMENT_ALLOCATE_PAY_SLIP_NO;
    private String FPAYMENT_ALLOCATE_PAY_DRAFT_NO;
    private String FPAYMENT_ALLOCATE_COMMON_REFNO;
    private String FPAYMENT_ALLOCATE_PAY_CHEQUE_DATE;

    public String getFPAYMENT_ALLOCATE_PAY_CHEQUE_DATE() {
        return FPAYMENT_ALLOCATE_PAY_CHEQUE_DATE;
    }

    public void setFPAYMENT_ALLOCATE_PAY_CHEQUE_DATE(String FPAYMENT_ALLOCATE_PAY_CHEQUE_DATE) {
        this.FPAYMENT_ALLOCATE_PAY_CHEQUE_DATE = FPAYMENT_ALLOCATE_PAY_CHEQUE_DATE;
    }

    public String getFPAYMENT_ALLOCATE_PAY_REF_NO() {
        return FPAYMENT_ALLOCATE_PAY_REF_NO;
    }

    public void setFPAYMENT_ALLOCATE_PAY_REF_NO(String FPAYMENT_ALLOCATE_PAY_REF_NO) {
        this.FPAYMENT_ALLOCATE_PAY_REF_NO = FPAYMENT_ALLOCATE_PAY_REF_NO;
    }

    public String getFPAYMENT_ALLOCATE_COMMON_REFNO() {
        return FPAYMENT_ALLOCATE_COMMON_REFNO;
    }

    public void setFPAYMENT_ALLOCATE_COMMON_REFNO(String FPAYMENT_ALLOCATE_COMMON_REFNO) {
        this.FPAYMENT_ALLOCATE_COMMON_REFNO = FPAYMENT_ALLOCATE_COMMON_REFNO;
    }

    public String getFPAYMENT_ALLOCATE_ID() {
        return FPAYMENT_ALLOCATE_ID;
    }

    public void setFPAYMENT_ALLOCATE_ID(String FPAYMENT_ALLOCATE_ID) {
        this.FPAYMENT_ALLOCATE_ID = FPAYMENT_ALLOCATE_ID;
    }

    public String getFPAYMENT_ALLOCATE_REFNO() {
        return FPAYMENT_ALLOCATE_REFNO;
    }

    public void setFPAYMENT_ALLOCATE_REFNO(String FPAYMENT_ALLOCATE_REFNO) {
        this.FPAYMENT_ALLOCATE_REFNO = FPAYMENT_ALLOCATE_REFNO;
    }

    public String getFPAYMENT_ALLOCATE_FDD_REFNO() {
        return FPAYMENT_ALLOCATE_FDD_REFNO;
    }

    public void setFPAYMENT_ALLOCATE_FDD_REFNO(String FPAYMENT_ALLOCATE_FDD_REFNO) {
        this.FPAYMENT_ALLOCATE_FDD_REFNO = FPAYMENT_ALLOCATE_FDD_REFNO;
    }

    public String getFPAYMENT_ALLOCATE_FDD_TXN_DATE() {
        return FPAYMENT_ALLOCATE_FDD_TXN_DATE;
    }

    public void setFPAYMENT_ALLOCATE_FDD_TXN_DATE(String FPAYMENT_ALLOCATE_FDD_TXN_DATE) {
        this.FPAYMENT_ALLOCATE_FDD_TXN_DATE = FPAYMENT_ALLOCATE_FDD_TXN_DATE;
    }

    public String getFPAYMENT_ALLOCATE_FDD_PAID_AMT() {
        return FPAYMENT_ALLOCATE_FDD_PAID_AMT;
    }

    public void setFPAYMENT_ALLOCATE_FDD_PAID_AMT(String FPAYMENT_ALLOCATE_FDD_PAID_AMT) {
        this.FPAYMENT_ALLOCATE_FDD_PAID_AMT = FPAYMENT_ALLOCATE_FDD_PAID_AMT;
    }

    public String getFPAYMENT_ALLOCATE_FDD_TOTAL_BAL() {
        return FPAYMENT_ALLOCATE_FDD_TOTAL_BAL;
    }

    public void setFPAYMENT_ALLOCATE_FDD_TOTAL_BAL(String FPAYMENT_ALLOCATE_FDD_TOTAL_BAL) {
        this.FPAYMENT_ALLOCATE_FDD_TOTAL_BAL = FPAYMENT_ALLOCATE_FDD_TOTAL_BAL;
    }

    public String getFPAYMENT_ALLOCATE_PAY_MODE() {
        return FPAYMENT_ALLOCATE_PAY_MODE;
    }

    public void setFPAYMENT_ALLOCATE_PAY_MODE(String FPAYMENT_ALLOCATE_PAY_MODE) {
        this.FPAYMENT_ALLOCATE_PAY_MODE = FPAYMENT_ALLOCATE_PAY_MODE;
    }

    public String getFPAYMENT_ALLOCATE_PAY_DATE() {
        return FPAYMENT_ALLOCATE_PAY_DATE;
    }

    public void setFPAYMENT_ALLOCATE_PAY_DATE(String FPAYMENT_ALLOCATE_PAY_DATE) {
        this.FPAYMENT_ALLOCATE_PAY_DATE = FPAYMENT_ALLOCATE_PAY_DATE;
    }

    public String getFPAYMENT_ALLOCATE_PAY_AMT() {
        return FPAYMENT_ALLOCATE_PAY_AMT;
    }

    public void setFPAYMENT_ALLOCATE_PAY_AMT(String FPAYMENT_ALLOCATE_PAY_AMT) {
        this.FPAYMENT_ALLOCATE_PAY_AMT = FPAYMENT_ALLOCATE_PAY_AMT;
    }

    public String getFPAYMENT_ALLOCATE_PAY_REM_AMT() {
        return FPAYMENT_ALLOCATE_PAY_REM_AMT;
    }

    public void setFPAYMENT_ALLOCATE_PAY_REM_AMT(String FPAYMENT_ALLOCATE_PAY_REM_AMT) {
        this.FPAYMENT_ALLOCATE_PAY_REM_AMT = FPAYMENT_ALLOCATE_PAY_REM_AMT;
    }

    public String getFPAYMENT_ALLOCATE_PAY_ALLO_AMT() {
        return FPAYMENT_ALLOCATE_PAY_ALLO_AMT;
    }

    public void setFPAYMENT_ALLOCATE_PAY_ALLO_AMT(String FPAYMENT_ALLOCATE_PAY_ALLO_AMT) {
        this.FPAYMENT_ALLOCATE_PAY_ALLO_AMT = FPAYMENT_ALLOCATE_PAY_ALLO_AMT;
    }

    public String getFPAYMENT_ALLOCATE_PAY_BANK() {
        return FPAYMENT_ALLOCATE_PAY_BANK;
    }

    public void setFPAYMENT_ALLOCATE_PAY_BANK(String FPAYMENT_ALLOCATE_PAY_BANK) {
        this.FPAYMENT_ALLOCATE_PAY_BANK = FPAYMENT_ALLOCATE_PAY_BANK;
    }

    public String getFPAYMENT_ALLOCATE_PAY_CHEQUE_NO() {
        return FPAYMENT_ALLOCATE_PAY_CHEQUE_NO;
    }

    public void setFPAYMENT_ALLOCATE_PAY_CHEQUE_NO(String FPAYMENT_ALLOCATE_PAY_CHEQUE_NO) {
        this.FPAYMENT_ALLOCATE_PAY_CHEQUE_NO = FPAYMENT_ALLOCATE_PAY_CHEQUE_NO;
    }

    public String getFPAYMENT_ALLOCATE_PAY_CREDIT_CARD_NO() {
        return FPAYMENT_ALLOCATE_PAY_CREDIT_CARD_NO;
    }

    public void setFPAYMENT_ALLOCATE_PAY_CREDIT_CARD_NO(String FPAYMENT_ALLOCATE_PAY_CREDIT_CARD_NO) {
        this.FPAYMENT_ALLOCATE_PAY_CREDIT_CARD_NO = FPAYMENT_ALLOCATE_PAY_CREDIT_CARD_NO;
    }

    public String getFPAYMENT_ALLOCATE_PAY_SLIP_NO() {
        return FPAYMENT_ALLOCATE_PAY_SLIP_NO;
    }

    public void setFPAYMENT_ALLOCATE_PAY_SLIP_NO(String FPAYMENT_ALLOCATE_PAY_SLIP_NO) {
        this.FPAYMENT_ALLOCATE_PAY_SLIP_NO = FPAYMENT_ALLOCATE_PAY_SLIP_NO;
    }

    public String getFPAYMENT_ALLOCATE_PAY_DRAFT_NO() {
        return FPAYMENT_ALLOCATE_PAY_DRAFT_NO;
    }

    public void setFPAYMENT_ALLOCATE_PAY_DRAFT_NO(String FPAYMENT_ALLOCATE_PAY_DRAFT_NO) {
        this.FPAYMENT_ALLOCATE_PAY_DRAFT_NO = FPAYMENT_ALLOCATE_PAY_DRAFT_NO;
    }
}
